name: Gatewaytest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#118d8b'
    - '#008080'
    - '#008b8b'
    - '#108080'
    - '#005555'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
